[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "aedge:trading"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.24.0", features = ["default"] }
